# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys

from SIFT import SIFT

class Ui_MainWindow(object):

    def __init__(self):
        self.sift = SIFT()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(233, 448)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 171, 371))
        self.groupBox.setObjectName("groupBox")

        self.loadImage1 = QtWidgets.QPushButton(self.groupBox)
        self.loadImage1.setGeometry(QtCore.QRect(20, 50, 131, 41))
        self.loadImage1.setObjectName("loadImage1")
        self.loadImage1.clicked.connect(self.LoadImage1Clicked)

        self.loadImage2 = QtWidgets.QPushButton(self.groupBox)
        self.loadImage2.setGeometry(QtCore.QRect(20, 130, 131, 41))
        self.loadImage2.setObjectName("loadImage2")
        self.loadImage2.clicked.connect(self.LoadImage2Clicked)


        self.keypoints = QtWidgets.QPushButton(self.groupBox)
        self.keypoints.setGeometry(QtCore.QRect(20, 210, 131, 41))
        self.keypoints.setObjectName("keyPoints")
        self.keypoints.clicked.connect(self.KeypointsClicked)

        self.matchedKeypoints = QtWidgets.QPushButton(self.groupBox)
        self.matchedKeypoints.setGeometry(QtCore.QRect(20, 290, 131, 41))
        self.matchedKeypoints.setObjectName("matchedKeypoints")
        self.matchedKeypoints.clicked.connect(self.MatchedKeypointsClicked)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 233, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "4. SIFT"))
        self.loadImage1.setText(_translate("MainWindow", "Load Image 1"))
        self.loadImage2.setText(_translate("MainWindow", "Load Image 2"))
        self.keypoints.setText(_translate("MainWindow", "4.1 Keypoints"))
        self.matchedKeypoints.setText(_translate("MainWindow", "4.2 Matched Keypoints"))

    def LoadImage1Clicked(self):
        fileName = QtWidgets.QFileDialog.getOpenFileName(None, 'OpenFile', './')
        self.sift.LoadImage1(fileName[0])

    def LoadImage2Clicked(self):
        fileName = QtWidgets.QFileDialog.getOpenFileName(None, 'OpenFile', './')
        self.sift.LoadImage2(fileName[0])

    def KeypointsClicked(self):
        self.sift.Keypoints()

    def MatchedKeypointsClicked(self):
        self.sift.MatchedKeypoints()

