# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from Cifar10 import Cifar10

class Ui_MainWindow(object):

    def __init__(self):
        self.cifar10 = Cifar10()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 291, 461))
        self.groupBox.setObjectName("groupBox")

        self.loadImage = QtWidgets.QPushButton(self.groupBox)
        self.loadImage.setGeometry(QtCore.QRect(30, 50, 231, 31))
        self.loadImage.setObjectName("loadImage")
        self.loadImage.clicked.connect(self.LoadImageClicked)

        self.showTrainImages = QtWidgets.QPushButton(self.groupBox)
        self.showTrainImages.setGeometry(QtCore.QRect(30, 120, 231, 31))
        self.showTrainImages.setObjectName("showTrainImages")
        self.showTrainImages.clicked.connect(self.ShowTrainImagesClicked)

        self.showModelStructure = QtWidgets.QPushButton(self.groupBox)
        self.showModelStructure.setGeometry(QtCore.QRect(30, 190, 231, 31))
        self.showModelStructure.setObjectName("showModelStructure")
        self.showModelStructure.clicked.connect(self.ShowModelStructureClicked)

        self.showDataAugmentation = QtWidgets.QPushButton(self.groupBox)
        self.showDataAugmentation.setGeometry(QtCore.QRect(30, 260, 231, 31))
        self.showDataAugmentation.setObjectName("showDataAugmentation")
        self.showDataAugmentation.clicked.connect(self.ShowDataAugmentationClicked)


        self.showAccuracyAndLoss = QtWidgets.QPushButton(self.groupBox)
        self.showAccuracyAndLoss.setGeometry(QtCore.QRect(30, 330, 231, 31))
        self.showAccuracyAndLoss.setObjectName("showAccuracyAndLoss")
        self.showAccuracyAndLoss.clicked.connect(self.ShowAccuracyAndLossClicked)


        self.inference = QtWidgets.QPushButton(self.groupBox)
        self.inference.setGeometry(QtCore.QRect(30, 390, 231, 31))
        self.inference.setObjectName("inference")
        self.inference.clicked.connect(self.InferenceClicked)

        self.qLabel = QtWidgets.QLabel(self.centralwidget)
        self.qLabel.setGeometry(QtCore.QRect(370, 120, 391, 351))
        self.qLabel.setObjectName("qLabel")

        self.txt1 = QtWidgets.QLabel(self.centralwidget)
        self.txt1.setGeometry(QtCore.QRect(370, 30, 480, 80))
        self.txt1.setObjectName("txt1")
        self.txt1.setStyleSheet('font-size:30px;')

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "5.Resnet101 Test"))
        self.loadImage.setText(_translate("MainWindow", "Load Image"))
        self.showTrainImages.setText(_translate("MainWindow", "1.Show Train Images"))
        self.showModelStructure.setText(_translate("MainWindow", "2.Show Model Structure"))
        self.showDataAugmentation.setText(_translate("MainWindow", "3.Show Data Augmentation"))
        self.showAccuracyAndLoss.setText(_translate("MainWindow", "4.Show Accuracy and Loss"))
        self.inference.setText(_translate("MainWindow", "5.Inference"))

    def ShowTrainImagesClicked(self):
        self.cifar10.ShowTrainImages()

    def ShowModelStructureClicked(self):
        self.cifar10.ShowModelStructure()

    def LoadImageClicked(self):
        fileName = QtWidgets.QFileDialog.getOpenFileName(None, 'OpenFile', './')

        pix = QtGui.QPixmap(fileName[0])
        self.qLabel.setPixmap(pix)

        self.cifar10.LoadImage(fileName[0])



    def ShowDataAugmentationClicked(self):
        self.cifar10.ShowDataAugmentation()

    def ShowAccuracyAndLossClicked(self):
        self.cifar10.ShowAccuracyAndLoss()

        pix = QtGui.QPixmap('accAndLoss.png')
        self.qLabel.setPixmap(pix)

        self.cifar10.LoadImage('accAndLoss.png')

    def InferenceClicked(self):

        p,c = self.cifar10.Inference()
        self.txt1.setText('Confidence = '+str(p)+'\n'+'Prediction Label: '+c)
        
        